apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskweb-deployment
  labels:
    app: flaskweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskweb
  template:
    metadata:
      labels:
        app: flaskweb
    spec:
      containers:
        - name: flaskweb
          image: cithit/roseaw:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskweb-service
spec:
  type: LoadBalancer 
#  loadBalancerIP: 10.48.10.116                                     
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: flaskweb 
